### ISSUE TITLE
repo rename

### ISSUE THREAD

**Issue by alistair-broomhead** [russel/pip_update#1]
@alyphen @russel I'd like to rename the repo, and the tool, to pip_upgrade.

This would mirror apt-get, and would leave a pip_update command free to refresh a cache, which could be used by pip_bash_autocomplete as well as other tools. I'm going to go ahead and change the name of the tool, but I wanted to get peoples' sign-off before changing the repo name, as this will break peoples' link to their remote.

**Comment by russel** [comment]
@alyphen @alistair-broomhead Sounds fine to me. Perhaps you want to try doing it to check you have "owner" privilege on this repository.

**Comment by alistair-broomhead** [comment]
@russel I do not appear to have the owner privilege, or at least the repo settings button is not appearing for me

**Comment by alistair-broomhead** [comment]
@russel confirmed - I have forked the repo and was able to rename the fork under github.com/alistair-broomhead/pip_upgrade/settings however github.com/russel/pip_update/settings returns a 404 for me

**Comment by russel** [comment]
OK, I'll rename it now.
